/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KargoRouteImport } from './routes/_kargo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KargoWhLoaderRouteImport } from './routes/_kargo.wh-loader'
import { Route as KargoMerchantRouteImport } from './routes/_kargo.merchant'
import { Route as KargoDriver2RouteImport } from './routes/_kargo.driver2'
import { Route as KargoDriver1RouteImport } from './routes/_kargo.driver1'
import { Route as KargoCoordOpRouteImport } from './routes/_kargo.coord-op'
import { Route as KargoCoordKuposRouteImport } from './routes/_kargo.coord-kupos'

const KargoRoute = KargoRouteImport.update({
  id: '/_kargo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KargoWhLoaderRoute = KargoWhLoaderRouteImport.update({
  id: '/wh-loader',
  path: '/wh-loader',
  getParentRoute: () => KargoRoute,
} as any)
const KargoMerchantRoute = KargoMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => KargoRoute,
} as any)
const KargoDriver2Route = KargoDriver2RouteImport.update({
  id: '/driver2',
  path: '/driver2',
  getParentRoute: () => KargoRoute,
} as any)
const KargoDriver1Route = KargoDriver1RouteImport.update({
  id: '/driver1',
  path: '/driver1',
  getParentRoute: () => KargoRoute,
} as any)
const KargoCoordOpRoute = KargoCoordOpRouteImport.update({
  id: '/coord-op',
  path: '/coord-op',
  getParentRoute: () => KargoRoute,
} as any)
const KargoCoordKuposRoute = KargoCoordKuposRouteImport.update({
  id: '/coord-kupos',
  path: '/coord-kupos',
  getParentRoute: () => KargoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coord-kupos': typeof KargoCoordKuposRoute
  '/coord-op': typeof KargoCoordOpRoute
  '/driver1': typeof KargoDriver1Route
  '/driver2': typeof KargoDriver2Route
  '/merchant': typeof KargoMerchantRoute
  '/wh-loader': typeof KargoWhLoaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coord-kupos': typeof KargoCoordKuposRoute
  '/coord-op': typeof KargoCoordOpRoute
  '/driver1': typeof KargoDriver1Route
  '/driver2': typeof KargoDriver2Route
  '/merchant': typeof KargoMerchantRoute
  '/wh-loader': typeof KargoWhLoaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_kargo': typeof KargoRouteWithChildren
  '/_kargo/coord-kupos': typeof KargoCoordKuposRoute
  '/_kargo/coord-op': typeof KargoCoordOpRoute
  '/_kargo/driver1': typeof KargoDriver1Route
  '/_kargo/driver2': typeof KargoDriver2Route
  '/_kargo/merchant': typeof KargoMerchantRoute
  '/_kargo/wh-loader': typeof KargoWhLoaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coord-kupos'
    | '/coord-op'
    | '/driver1'
    | '/driver2'
    | '/merchant'
    | '/wh-loader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coord-kupos'
    | '/coord-op'
    | '/driver1'
    | '/driver2'
    | '/merchant'
    | '/wh-loader'
  id:
    | '__root__'
    | '/'
    | '/_kargo'
    | '/_kargo/coord-kupos'
    | '/_kargo/coord-op'
    | '/_kargo/driver1'
    | '/_kargo/driver2'
    | '/_kargo/merchant'
    | '/_kargo/wh-loader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KargoRoute: typeof KargoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kargo': {
      id: '/_kargo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kargo/wh-loader': {
      id: '/_kargo/wh-loader'
      path: '/wh-loader'
      fullPath: '/wh-loader'
      preLoaderRoute: typeof KargoWhLoaderRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/merchant': {
      id: '/_kargo/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof KargoMerchantRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/driver2': {
      id: '/_kargo/driver2'
      path: '/driver2'
      fullPath: '/driver2'
      preLoaderRoute: typeof KargoDriver2RouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/driver1': {
      id: '/_kargo/driver1'
      path: '/driver1'
      fullPath: '/driver1'
      preLoaderRoute: typeof KargoDriver1RouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/coord-op': {
      id: '/_kargo/coord-op'
      path: '/coord-op'
      fullPath: '/coord-op'
      preLoaderRoute: typeof KargoCoordOpRouteImport
      parentRoute: typeof KargoRoute
    }
    '/_kargo/coord-kupos': {
      id: '/_kargo/coord-kupos'
      path: '/coord-kupos'
      fullPath: '/coord-kupos'
      preLoaderRoute: typeof KargoCoordKuposRouteImport
      parentRoute: typeof KargoRoute
    }
  }
}

interface KargoRouteChildren {
  KargoCoordKuposRoute: typeof KargoCoordKuposRoute
  KargoCoordOpRoute: typeof KargoCoordOpRoute
  KargoDriver1Route: typeof KargoDriver1Route
  KargoDriver2Route: typeof KargoDriver2Route
  KargoMerchantRoute: typeof KargoMerchantRoute
  KargoWhLoaderRoute: typeof KargoWhLoaderRoute
}

const KargoRouteChildren: KargoRouteChildren = {
  KargoCoordKuposRoute: KargoCoordKuposRoute,
  KargoCoordOpRoute: KargoCoordOpRoute,
  KargoDriver1Route: KargoDriver1Route,
  KargoDriver2Route: KargoDriver2Route,
  KargoMerchantRoute: KargoMerchantRoute,
  KargoWhLoaderRoute: KargoWhLoaderRoute,
}

const KargoRouteWithChildren = KargoRoute._addFileChildren(KargoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KargoRoute: KargoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
